### ISSUE TITLE
README.md need some general information

### ISSUE THREAD

**Issue by kasperbirk** [Batrium/WatchMonUdpListener#1]
Could there be added som general information in README.md about how to connect the watchmon(hardware) to mqtt and/or influxdb?

**Comment by daromer2** [comment]
All information on how to connect the listener is under the Install section. Both on how to enable each message and how to setup where the server is located. 
Note that this is only for the software that is written and not about the hardware. The hardware part is discussed on the webpage www.batrium.com

Note that InfluxDB support does not exist in the HW and MQTT is not officially released yet. It will be announced in time.
