### ISSUE TITLE
influx user/pwd

### ISSUE THREAD

**Issue by jordipalet** [Batrium/WatchMonUdpListener#10]
In the previous version, I've not created any specific user/password in influx, but it seems that this version assumes that root/root is there.

Before that I was getting no data and the error message:
A 401 Unauthorized error occurred: {"error":"authorization failed"}\n' }

I think it will be good to make sure that you can change in the config.json or another file the user and password, so it matches your own security policy.

**Comment by daromer2** [comment]
Will take a look at that and add it. I will also add enable/disable on MQTT and Influx :)  Earlier versions of Influx basically had the default so didnt bother but it should for sure be there.

**Comment by daromer2** [comment]
I added it to config. Though I dont consider ports nor https. Added a quick check and it exists if needed.  
Please test https://github.com/Batrium/WatchMonUdpListener/commit/77538f80035fd93c4d8a526c70e1e0491ebeb8b7
