### ISSUE TITLE
DataStruckture Change with WachMon 2.15.10

### ISSUE THREAD

**Issue by CityJumperAC** [Batrium/WatchMonUdpListener#6]
With the Last WachMon 2.15.10 there is a change in UDP Data Structure, so some (a lot) of measurements are not longer function.

Most from Status Rapid. I will try to fix it by Myself, but would be nice to recive an update here!

Greetz
Michael

**Comment by jaronw** [comment]
inclusion of payload messages for SW2.15 onwards have been added
