### ISSUE TITLE
config/config.json not being created?

### ISSUE THREAD

**Issue by jordipalet** [Batrium/WatchMonUdpListener#9]
I'd copied config.json_dist and modified into config.json (as I did in the previous version) and it was not working.

Then checking the source code I saw that now is being read from the config directory and if doesn't exist, created there:
	var config = JSON.parse(fs.readFileSync('config/config.json', "utf8"));

However this was not happening for me (I'm using a Raspberry Pi 4).

So I just changed the code to 

	var config = JSON.parse(fs.readFileSync('config.json', "utf8"));

and resolved the issue for my case.

**Comment by daromer2** [comment]
It should create and move the file. I want it in that directory so it can be pulled out when running it in a container.
Fixed in https://github.com/Batrium/WatchMonUdpListener/commit/35146bf95740723e4f30045466510f72c9c33042
